[package]
edition = "2018"
name = "zk-paillier"
version = "0.4.3"
authors = ["Gary <gary@kzencorp.com>", "Morten Dahl <mortendahlcs@gmail.com>", "Omer <omer.shlomovits@gmail.com>"]
description = "Collection of Paillier cryptosystem zero knowledge proofs written in Rust"
keywords = ["paillier", "homomorphic", "encryption", "zero-knowledge", "cryptoagorithms"]
categories = ["cryptography", "algorithms"]
license = "GPL-3.0-or-later"
repository = "https://github.com/ZenGo-X/zk-paillier"

[lib]
crate-type = ["lib"]

[dependencies.bit-vec]
version = "0.6"

[dependencies.curv-kzen]
# version = "0.9"
path = "../curv-kzen-0.9.0"
default-features = false

[dependencies.digest]
version = "0.9"

[dependencies.paillier]
package = "kzen-paillier"
# version = "0.4"
path = "../kzen-paillier-0.4.2"
default-features = false

[dependencies.rand]
version = "0.6"

[dependencies.rayon]
version = "1.1"

[dependencies.serde]
version = "1.0"
features = ["derive"]

[dependencies.sha2]
version = "0.9"

[dependencies.thiserror]
version = "1"
[dev-dependencies.criterion]
version = "0.3"

[features]
default = ["curv-kzen/num-bigint"]
