[package]
edition = "2018"
name = "kzen-paillier"
version = "0.4.2"
description = "Efficient pure-Rust library for the Paillier partially homomorphic encryption scheme"
keywords = ["paillier", "homomorphic", "encryption", "zero-knowledge", "cryptoagorithms"]
categories = ["cryptography", "algorithms"]
license = "MIT OR Apache-2.0"
repository = "https://github.com/ZenGo-X/rust-paillier"

[dependencies.curv-kzen]
# version = "0.9"
path = "../curv-kzen-0.9.0"
default-features = false

[dependencies.rayon]
version = "1.1"

[dependencies.serde]
version = "1.0"
features = ["derive"]

[dev-dependencies.bencher]
version = "0.1"

[dev-dependencies.rand]
version = "0.6"

[dev-dependencies.serde_json]
version = "1.0"

[features]
default = ["curv-kzen/num-bigint"]
