[workspace]

[package]
name = "protoc_rust"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "protoc_rust"
path = "main.rs"

[dependencies]
clap = "4"
glob = "0.3"
tonic-build = { version = "0.11", features = ["prost"] }

[profile.release]
opt-level = 3
strip = true
